[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CBI-R Docs"
authors = [{name = "Alice", email = "omero.notifications@gmail.com"}]
version = "0.1.0"
description = "CBI-R Docs Project"