[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CBI-R Processes"
authors = [{name = "Alice Kang", email = "omero.notifications@gmail.com"}]
dynamic = ["version", "description"]
